name: llmbo

dependencies:
  - python=3.11
  - pip
  - pip:
    - pymoo==0.6.0.1
    - jax==0.4.18
    - jaxlib==0.4.18
    - scipy==1.11.3
    - matplotlib==3.8.0
    - pandas==2.1.1
    - numpy==1.26.0
    - openai==0.28.1
    - tensorflow-probability==0.19.0
    - gpjax==0.6.9
    - optax==0.1.7
    - jaxopt==0.8.1
    - llama-cpp-python
    